# Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  labels:
    app: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: rails-env-config
        image: recario/server:latest
        name: sidekiq
        command: ["bundle", "exec", "sidekiq", "-q", "default", "-q", "contacts", "-q", "sms", "-q", "notifications"]
